In [12]:
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras import Sequential, layers, Input
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout, LSTM
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import LearningRateScheduler
import tensorflow.keras.backend as K
import os
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
from tensorflow.keras.initializers import Constant
from tensorflow.keras.initializers import RandomNormal, HeNormal, GlorotNormal
import cv2
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, accuracy_score

from sklearn.model_selection import train_test_split


# In[2]:


#溶氧量點數
def DO_value(num):
  if (num >= 6.5):
    return 1
  elif(num >= 4.6):
    return 3
  elif(num >= 2.0):
    return 6
  else:
    return 10

#懸浮固體點數
def TSS_value(num):
  if (num <= 20.0):
    return 1
  elif(num <= 49.9):
    return 3
  elif(num <= 100):
    return 6
  else:
    return 10

#生化需氧量點數
def BOD_value(num):
  if (num <= 3.0):
    return 1
  elif(num <= 4.9):
    return 3
  elif(num <= 15.0):
    return 6
  else:
    return 10

#氨氣點數
def NH3N_value(num):
  if (num <= 0.5):
    return 1
  elif(num <= 0.99):
    return 3
  elif(num <= 3.0):
    return 6
  else:
    return 10

#計算RPI(River Pollution Index)
def cal_RPI(DO, TSS, BOD, NH3N):
  DO_num = DO_value(DO)
  TSS_num = TSS_value(TSS)
  BOD_num = BOD_value(BOD)
  NH3N_num = NH3N_value(NH3N)
  return (DO_num + TSS_num + BOD_num + NH3N_num)/4


# In[3]:


# RPI = (DO + SS + BOD + NH3N) / 4
# NH3-N / NO3-N = K  -->  NH3-N = NO3-N * K


# In[4]:


# def cal_RPI(DO, SS, BOD, NH3N):
#     return (DO + SS + BOD + NH3N) / 4


# In[5]:


APRIL_RPI = cal_RPI(9.0 ,15, 0 ,1.3/4.5)
MAY_RPI = cal_RPI(8.4, 10, 0, 2.5/4.5)
JUNE_RPI = cal_RPI(8.5, 16, 0, 1.7/4.5)
JULY_RPI = cal_RPI(6.4, 24, 0, 2.6/4.5)
AUGUST_RPI = cal_RPI(8.1, 143, 0, 1.2/4.5)
SEPTEMBER_RPI = cal_RPI(7.7, 53, 0, 1.5/4.5)
OCTOBER_RPI = cal_RPI(7.8, 23, 0, 1.2 / 4.5)


# In[6]:


# Printing the calculated values
print("April RPI:", APRIL_RPI)
print("May RPI:", MAY_RPI)
print("June RPI:", JUNE_RPI)
print("July RPI:", JULY_RPI)
print("August RPI:", AUGUST_RPI)
print("September RPI:", SEPTEMBER_RPI)
print("October PRI:", OCTOBER_RPI)


# In[7]:


# todo: change the label
def get_label(val):
    if val <= 2.0:
        return "NP"
    elif val <= 3.0:
        return "SP"
    elif val <= 6.0:
        return "MP"
    else:
        return "SEVERE"


# In[8]:


folder_paths = ['./水質檢測/Image_data/1_April',
                './水質檢測/Image_data/2_May',
                './水質檢測/Image_data/3_June',
                './水質檢測/Image_data/4_July',
                './水質檢測/Image_data/5_August',
                './水質檢測/Image_data/6_September']
labels = [get_label(APRIL_RPI), get_label(MAY_RPI), get_label(JUNE_RPI), 
          get_label(JULY_RPI), get_label(AUGUST_RPI), get_label(SEPTEMBER_RPI)]  # 对应文件夹1和文件夹2的标签


oct_paths = ["./水質檢測/Image_data/7_October"]
oct_label_Stirng = [get_label(OCTOBER_RPI)]


import tensorflow as tf
import os

def load_and_label_images(folder_path, label):
    image_paths = []  # 存储图像文件的路径
    labels = []       # 存储图像对应的标签

    # 获取文件夹中的所有图像文件的路径
    for filename in os.listdir(folder_path):
        if filename.endswith('.jpg') or filename.endswith('.png'):  # 假设只加载jpg和png格式的图像文件
            image_paths.append(os.path.join(folder_path, filename))
            labels.append(label)

    # 加载图像并为其指定标签
    images = [tf.io.read_file(image_path) for image_path in image_paths]
    images = [tf.image.decode_image(image, channels=3) for image in images]

    # 可选的数据预处理：这里假设对图像进行归一化
    #images = [tf.cast(image, tf.float32) / 255.0 for image in images]

    return images, labels



# 你可以根据需要加载多个文件夹中的图像并为其指定不同的标签
# folder_paths = ['/path/to/folder1', '/path/to/folder2']
# labels = [1, 2]  # 对应文件夹1和文件夹2的标签

# 加载所有文件夹中的图像和标签
all_images = []
all_labels = []
for folder_path, label in zip(folder_paths, labels):
    images, labels = load_and_label_images(folder_path, label)
    all_images.extend(images)
    all_labels.extend(labels)
    

oct_images = []
oct_labels = []
for oct_path, label in zip(oct_paths, oct_label_Stirng):
    images, labels = load_and_label_images(oct_path, oct_label_Stirng)
    images_resized = [tf.image.resize(img, (224, 224)) for img  in images]
    oct_images.extend(images_resized)
    oct_labels.extend(labels)


# In[11]:


# print(all_labels)
# print(oct_labels)

label_mapping = {
    "NP":[1,0,0],
    "MP":[0,1,0],
    "SP":[0,0,1]
}

# unique_labels_list = list(set(all_labels))
# unique_labels_list.sort()
# label_to_index = {label: index for index, label in enumerate(unique_labels_list)}
# label_one_hot = [tf.one_hot(label_to_index[label], len(unique_labels_list)) for label in all_labels]
label_one_hot = [label_mapping[label] for label in all_labels]
oct_label_one_hot = [label_mapping[label[0]] for label in oct_labels]


# In[12]:


print(len(all_images))
print(all_images[0].shape)
print(len(label_one_hot))
print(label_one_hot[0:10])

print("=============================")

print(len(oct_images))
print(oct_images[0].shape)
print(len(oct_label_one_hot))
print(oct_label_one_hot[0:10])


# In[13]:


# train_images, validation_images, train_labels, validation_labels = train_test_split(all_images, label_one_hot, test_size=0.2, random_state=42)

# # 创建训练集数据集
# train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
# train_dataset = train_dataset.shuffle(buffer_size=len(train_images)).batch(batch_size=32)

# # 创建验证集数据集
# validation_dataset = tf.data.Dataset.from_tensor_slices((validation_images, validation_labels))
# validation_dataset = validation_dataset.shuffle(buffer_size=len(validation_images)).batch(batch_size=32)

# 創建測試資料集
test_dataset = tf.data.Dataset.from_tensor_slices((oct_images, oct_label_one_hot))
test_dataset = test_dataset.shuffle(buffer_size=len(oct_images)).batch(batch_size=32)


# In[14]:


# # 构建数据集
# dataset = tf.data.Dataset.from_tensor_slices((all_images, label_one_hot))

# # 可选的打乱和分批处理
# dataset = dataset.shuffle(buffer_size=len(all_images)).batch(batch_size=32)


# In[15]:


# import matplotlib.pyplot as plt

# # 从数据集中获取并显示图像
# fig, axs = plt.subplots(2, 5, figsize=(20, 8))  # 创建一个2x5的子图布局

# for i, (image, label) in enumerate(dataset.take(10)):  # 取出前十张图像
#     row = i // 5  # 计算当前图像应该位于的行索引
#     col = i % 5   # 计算当前图像应该位于的列索引

#     axs[row, col].imshow(image[0])  # 假设每个batch里只有一张图像
#     axs[row, col].set_title('Label: {}'.format(label[0].numpy()))
#     axs[row, col].axis('off')  # 关闭坐标轴

# plt.show()


# In[16]:


# 定义一个简单的卷积神经网络模型

def create_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(224, 224, 3)),  # 減少過濾器數量
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(8, (3, 3), activation='relu'),  # 減少過濾器數量
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(4, (3, 3), activation='relu'),  # 減少過濾器數量
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(16, activation='relu'),  # 減少全連接層大小
        tf.keras.layers.Dense(3, activation='softmax')
    ])
    return model

print(create_model().summary())

# In[17]:


num_fold = 10
all_images = np.array(all_images)
label_one_hot = np.array(label_one_hot)

kf = KFold(n_splits=num_fold, shuffle=True, random_state=42)
fold = 1
confusion_matrices = []

for train_index, val_index in kf.split(all_images):
    print(f"Training fold {fold}...")
    # print(f"train_index={train_index}, val_index={val_index}")
    fold += 1
    
    train_images, val_images = all_images[train_index], all_images[val_index]
    train_labels, val_labels = label_one_hot[train_index], label_one_hot[val_index]
    
    # 創建數據集
    train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
    train_dataset = train_dataset.shuffle(buffer_size=len(train_images)).batch(32)
    
    val_dataset = tf.data.Dataset.from_tensor_slices((val_images, val_labels))
    val_dataset = val_dataset.batch(32)
    
    # 創建和編譯模型
    model = create_model()
    model.compile(optimizer='adam',
                  loss=tf.keras.losses.categorical_crossentropy,
                  metrics=['accuracy'])
    
    # 訓練模型
    model.fit(train_dataset, validation_data=val_dataset, epochs=3, callbacks=[
        tf.keras.callbacks.ModelCheckpoint(filepath=f'3_best_model_small_Kfold_{fold}.keras', 
                                           monitor='val_accuracy', 
                                           save_best_only=True, 
                                           mode='max', 
                                           verbose=1)
    ])
    
    # 評估模型
    model.load_weights(f'3_best_model_small_Kfold_{fold}.keras')
    
    # 使用模型預測
    predictions = model.predict(val_dataset)
    predicted_classes_index = np.argmax(predictions, axis=1)
    
    true_classes_index = np.argmax(val_labels, axis=1)
    
    # 計算混淆矩陣
    conf_matrix = confusion_matrix(true_classes_index, predicted_classes_index)
    confusion_matrices.append(conf_matrix)
    
    print("Confusion Matrix for fold {}:".format(fold))
    print(conf_matrix)
    model.save(f"3_model_small_Kfold_{fold}.h5")

# 平均混淆矩陣
average_conf_matrix = np.mean(confusion_matrices, axis=0)
print("Average Confusion Matrix:")
print(average_conf_matrix)



all_test_predictions = []

for fold in range(2, num_fold+2):
    model_name=f"3_model_small_Kfold_{fold}.h5"
    model = tf.keras.models.load_model(model_name)
    fold_predictions = model.predict(test_dataset)
    all_test_predictions.append(fold_predictions)
    
average_test_predictions = np.mean(all_test_predictions, axis=0)
predicted_classes_index = np.argmax(average_test_predictions, axis=1)


# In[26]:


print("average_test_predictions:", average_test_predictions)
print("predicted_classes_index:", predicted_classes_index)


# In[27]:


# 所有模型的預測結果的平均



true_classes_index = np.argmax([np.array(label) for label in oct_label_one_hot], axis=1)
# print(true_classes_index)

# print(f"({len(all_test_predictions)}, {len(all_test_predictions[0])}, {len(all_test_predictions[0][0])})")
# print(average_test_predictions.shape)
# print(predicted_classes_index.shape)
# print(average_test_predictions)

# # 計算confusion matrix
conf_matrix = confusion_matrix(true_classes_index, predicted_classes_index, labels=np.arange(3))

print("Confusion Matrix:")
print(conf_matrix)

# 计算准确率
accuracy = accuracy_score(true_classes_index, predicted_classes_index)
print("Accuracy:", accuracy)



April RPI: 1.0
May RPI: 1.5
June RPI: 1.0
July RPI: 2.5
August RPI: 3.25
September RPI: 2.25
October PRI: 1.5
9728
(224, 224, 3)
9728
[[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]]
625
(224, 224, 3)
625
[[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]]


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_44"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_94 (Conv2D)              │ (None, 222, 222, 16)   │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_132               │ (None, 111, 111, 16)   │             0 │
│ (MaxPooling2D)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_95 (Conv2D)              │ (None, 109, 109, 8)    │         1,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_133               │ (None, 54, 54, 8)      │             0 │
│ (MaxPooling2D)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_96 (Conv2D)              │ (None, 52, 52, 4)      │           292 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_134               │ (None, 26, 26, 4)      │             0 │
│ (MaxPooling2D)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_25 (Flatten)            │ (None, 2704)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_88 (Dense)                │ (None, 16)             │        43,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_89 (Dense)                │ (None, 3)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 45,231 (176.68 KB)

 Trainable params: 45,231 (176.68 KB)

 Non-trainable params: 0 (0.00 B)

None
Training fold 1...
Epoch 1/3
274/274 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5473 - loss: 4.8982
Epoch 1: val_accuracy improved from -inf to 0.91367, saving model to 3_best_model_small_Kfold_2.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 28s 101ms/step - accuracy: 0.5478 - loss: 4.8859 - val_accuracy: 0.9137 - val_loss: 0.3234
Epoch 2/3
274/274 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9463 - loss: 0.1795
Epoch 2: val_accuracy improved from 0.91367 to 0.98767, saving model to 3_best_model_small_Kfold_2.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 28s 100ms/step - accuracy: 0.9464 - loss: 0.1793 - val_accuracy: 0.9877 - val_loss: 0.0574
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.9937 - loss: 0.0295
Epoch 3: val_accuracy improved from 0.98767 to 0.99692, saving model to 3_best_model_small_Kfold_2.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.9937 - loss: 0.0295 - val_accuracy: 0.9969 - val_loss: 0.0128
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step


Confusion Matrix for fold 2:
[[497   0   2]
 [  0 178   0]
 [  1   0 295]]
Training fold 2...
Epoch 1/3


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.4865 - loss: 9.4739
Epoch 1: val_accuracy improved from -inf to 0.80987, saving model to 3_best_model_small_Kfold_3.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 21s 75ms/step - accuracy: 0.4870 - loss: 9.4244 - val_accuracy: 0.8099 - val_loss: 0.4355
Epoch 2/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9232 - loss: 0.2247
Epoch 2: val_accuracy improved from 0.80987 to 0.98869, saving model to 3_best_model_small_Kfold_3.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 75ms/step - accuracy: 0.9235 - loss: 0.2241 - val_accuracy: 0.9887 - val_loss: 0.0557
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9925 - loss: 0.0277
Epoch 3: val_accuracy did not improve from 0.98869
274/274 ━━━━━━━━━━━━━━━━━━━━ 21s 77ms/step - accuracy: 0.9925 - loss: 0.0277 - val_accuracy: 0.9887 - val_loss: 0.0506
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step


Confusion Matrix for fold 3:
[[524   0   3]
 [  6 160   0]
 [  2   0 278]]
Training fold 3...
Epoch 1/3


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5631 - loss: 16.5839
Epoch 1: val_accuracy improved from -inf to 0.98150, saving model to 3_best_model_small_Kfold_4.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - accuracy: 0.5644 - loss: 16.4939 - val_accuracy: 0.9815 - val_loss: 0.1093
Epoch 2/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9867 - loss: 0.0730
Epoch 2: val_accuracy improved from 0.98150 to 0.99075, saving model to 3_best_model_small_Kfold_4.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.9866 - loss: 0.0729 - val_accuracy: 0.9908 - val_loss: 0.0238
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9976 - loss: 0.0129
Epoch 3: val_accuracy improved from 0.99075 to 0.99794, saving model to 3_best_model_small_Kfold_4.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.9976 - loss: 0.0129 - val_accuracy: 0.9979 - val_loss: 0.0080
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step


Confusion Matrix for fold 4:
[[516   0   0]
 [  2 151   0]
 [  0   0 304]]
Training fold 4...
Epoch 1/3


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.4666 - loss: 7.3255
Epoch 1: val_accuracy improved from -inf to 0.56629, saving model to 3_best_model_small_Kfold_5.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 71ms/step - accuracy: 0.4670 - loss: 7.2889 - val_accuracy: 0.5663 - val_loss: 0.9740
Epoch 2/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5490 - loss: 0.9758
Epoch 2: val_accuracy improved from 0.56629 to 0.64851, saving model to 3_best_model_small_Kfold_5.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 73ms/step - accuracy: 0.5492 - loss: 0.9757 - val_accuracy: 0.6485 - val_loss: 0.8315
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.7927 - loss: 0.5277
Epoch 3: val_accuracy improved from 0.64851 to 0.99383, saving model to 3_best_model_small_Kfold_5.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 73ms/step - accuracy: 0.7935 - loss: 0.5259 - val_accuracy: 0.9938 - val_loss: 0.0304
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step


Confusion Matrix for fold 5:
[[529   2   1]
 [  1 147   0]
 [  1   1 291]]
Training fold 5...
Epoch 1/3


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5675 - loss: 1.0579
Epoch 1: val_accuracy improved from -inf to 0.97842, saving model to 3_best_model_small_Kfold_6.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - accuracy: 0.5689 - loss: 1.0544 - val_accuracy: 0.9784 - val_loss: 0.0842
Epoch 2/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9894 - loss: 0.0371
Epoch 2: val_accuracy improved from 0.97842 to 0.99383, saving model to 3_best_model_small_Kfold_6.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 71ms/step - accuracy: 0.9894 - loss: 0.0371 - val_accuracy: 0.9938 - val_loss: 0.0390
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9987 - loss: 0.0081
Epoch 3: val_accuracy improved from 0.99383 to 0.99486, saving model to 3_best_model_small_Kfold_6.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 69ms/step - accuracy: 0.9987 - loss: 0.0080 - val_accuracy: 0.9949 - val_loss: 0.0316
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step


Confusion Matrix for fold 6:
[[509   0   1]
 [  0 170   0]
 [  4   0 289]]
Training fold 6...
Epoch 1/3


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5703 - loss: 3.2731
Epoch 1: val_accuracy improved from -inf to 0.94656, saving model to 3_best_model_small_Kfold_7.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 69ms/step - accuracy: 0.5715 - loss: 3.2570 - val_accuracy: 0.9466 - val_loss: 0.1719
Epoch 2/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9675 - loss: 0.0996
Epoch 2: val_accuracy improved from 0.94656 to 0.98561, saving model to 3_best_model_small_Kfold_7.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.9676 - loss: 0.0995 - val_accuracy: 0.9856 - val_loss: 0.1001
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9915 - loss: 0.0307
Epoch 3: val_accuracy did not improve from 0.98561
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.9915 - loss: 0.0307 - val_accuracy: 0.9815 - val_loss: 0.0784
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step


Confusion Matrix for fold 7:
[[486   0   7]
 [  6 171   0]
 [  1   0 302]]
Training fold 7...
Epoch 1/3


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6351 - loss: 2.9809
Epoch 1: val_accuracy improved from -inf to 0.94347, saving model to 3_best_model_small_Kfold_8.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 71ms/step - accuracy: 0.6361 - loss: 2.9665 - val_accuracy: 0.9435 - val_loss: 0.1818
Epoch 2/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9803 - loss: 0.0840
Epoch 2: val_accuracy improved from 0.94347 to 0.99589, saving model to 3_best_model_small_Kfold_8.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 71ms/step - accuracy: 0.9803 - loss: 0.0838 - val_accuracy: 0.9959 - val_loss: 0.0134
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9981 - loss: 0.0062
Epoch 3: val_accuracy improved from 0.99589 to 0.99897, saving model to 3_best_model_small_Kfold_8.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 71ms/step - accuracy: 0.9981 - loss: 0.0062 - val_accuracy: 0.9990 - val_loss: 0.0041
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step


Confusion Matrix for fold 8:
[[501   0   1]
 [  0 172   0]
 [  0   0 299]]
Training fold 8...
Epoch 1/3


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.4842 - loss: 1.2932
Epoch 1: val_accuracy improved from -inf to 0.50360, saving model to 3_best_model_small_Kfold_9.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 71ms/step - accuracy: 0.4845 - loss: 1.2916 - val_accuracy: 0.5036 - val_loss: 1.0146
Epoch 2/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5975 - loss: 0.8903
Epoch 2: val_accuracy improved from 0.50360 to 0.96608, saving model to 3_best_model_small_Kfold_9.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 71ms/step - accuracy: 0.5983 - loss: 0.8887 - val_accuracy: 0.9661 - val_loss: 0.1301
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9802 - loss: 0.0847
Epoch 3: val_accuracy improved from 0.96608 to 0.99897, saving model to 3_best_model_small_Kfold_9.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 71ms/step - accuracy: 0.9803 - loss: 0.0846 - val_accuracy: 0.9990 - val_loss: 0.0093
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step


Confusion Matrix for fold 9:
[[468   0   0]
 [  0 178   0]
 [  0   1 326]]
Training fold 9...
Epoch 1/3


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5474 - loss: 1.9711
Epoch 1: val_accuracy improved from -inf to 0.98868, saving model to 3_best_model_small_Kfold_10.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 68ms/step - accuracy: 0.5484 - loss: 1.9633 - val_accuracy: 0.9887 - val_loss: 0.0598
Epoch 2/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9922 - loss: 0.0375
Epoch 2: val_accuracy improved from 0.98868 to 0.99280, saving model to 3_best_model_small_Kfold_10.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 68ms/step - accuracy: 0.9922 - loss: 0.0375 - val_accuracy: 0.9928 - val_loss: 0.0192
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9990 - loss: 0.0052
Epoch 3: val_accuracy improved from 0.99280 to 0.99691, saving model to 3_best_model_small_Kfold_10.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 69ms/step - accuracy: 0.9990 - loss: 0.0052 - val_accuracy: 0.9969 - val_loss: 0.0089
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step


Confusion Matrix for fold 10:
[[525   0   2]
 [  0 168   0]
 [  0   1 276]]
Training fold 10...
Epoch 1/3


/Users/future-outlier/miniconda3/envs/dev/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5459 - loss: 1.3842
Epoch 1: val_accuracy improved from -inf to 0.99588, saving model to 3_best_model_small_Kfold_11.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 20s 70ms/step - accuracy: 0.5472 - loss: 1.3790 - val_accuracy: 0.9959 - val_loss: 0.0210
Epoch 2/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9974 - loss: 0.0109
Epoch 2: val_accuracy improved from 0.99588 to 0.99897, saving model to 3_best_model_small_Kfold_11.keras
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.9974 - loss: 0.0109 - val_accuracy: 0.9990 - val_loss: 0.0089
Epoch 3/3
273/274 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9995 - loss: 0.0031
Epoch 3: val_accuracy did not improve from 0.99897
274/274 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.9995 - loss: 0.0030 - val_accuracy: 0.9990 - val_loss: 0.0031
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step


Confusion Matrix for fold 11:
[[485   1   0]
 [  0 184   0]
 [  0   0 302]]
Average Confusion Matrix:
[[5.040e+02 3.000e-01 1.700e+00]
 [1.500e+00 1.679e+02 0.000e+00]
 [9.000e-01 3.000e-01 2.962e+02]]


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
average_test_predictions: [[0.90637475 0.0538776  0.03974765]
 [0.7425831  0.06334529 0.19407156]
 [0.65112114 0.09704052 0.2518384 ]
 ...
 [0.5853682  0.03457094 0.38006085]
 [0.87298554 0.04195248 0.08506189]
 [0.80485475 0.00776969 0.18737555]]
predicted_classes_index: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0

In [ ]:
model.summary()